### ISSUE TITLE
0 reads pseudoaligned[~warn] no reads pseudoaligned

### ISSUE THREAD

**Issue by kaizen89** [pachterlab/kallistobustools#19]
Hi,
I am trying to follow the RNA velocity tutorial and using kb-python, after downloading the index file, the following command ends with an error
```
time kb count --h5ad -i index.idx -g transcripts_to_genes.txt -x 10xv3 -o SRR12603789 -c1 cdna_transcripts_to_capture.txt -c2 intron_transcripts_to_capture.txt --lamanno /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R1_001.fastq.gz /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R2_001.fastq.gz
[2021-02-19 20:56:06,115] WARNING The `--lamanno` and `-`-n`ucleus` flags are deprecated. These options will be removed in a future release. Please use `--workflow lamanno` or `--workflow nucleus` instead.
[2021-02-19 20:56:06,115]    INFO Using index index.idx to generate BUS file to SRR12603789 from
[2021-02-19 20:56:06,115]    INFO         /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R1_001.fastq.gz
[2021-02-19 20:56:06,115]    INFO         /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R2_001.fastq.gz
[2021-02-19 21:14:32,501]   ERROR 
[index] k-mer length: 31
[index] number of targets: 845,338
[index] number of k-mers: 271,648,279
[index] number of equivalence classes: 4,776,424
[quant] will process sample 1: /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R1_001.fastq.gz
/mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R2_001.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 819,658,242 reads, 0 reads pseudoaligned[~warn] no reads pseudoaligned.

[2021-02-19 21:14:32,501]   ERROR An exception occurred
Traceback (most recent call last):
  File "/home/salmon/.local/lib/python3.6/site-packages/kb_python/main.py", line 837, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/salmon/.local/lib/python3.6/site-packages/kb_python/main.py", line 218, in parse_count
    temp_dir=temp_dir
  File "/home/salmon/.local/lib/python3.6/site-packages/kb_python/count.py", line 1510, in count_velocity
    fastqs, index_paths[0], technology, out_dir, threads=threads
  File "/home/salmon/.local/lib/python3.6/site-packages/kb_python/validate.py", line 112, in inner
    results = func(*args, **kwargs)
  File "/home/salmon/.local/lib/python3.6/site-packages/kb_python/count.py", line 149, in kallisto_bus
    run_executable(command)
  File "/home/salmon/.local/lib/python3.6/site-packages/kb_python/dry/__init__.py", line 24, in inner
    return func(*args, **kwargs)
  File "/home/salmon/.local/lib/python3.6/site-packages/kb_python/utils.py", line 233, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/salmon/.local/lib/python3.6/site-packages/kb_python/bins/linux/kallisto/kallisto bus -i index.idx -o SRR12603789 -x 10xv3 -t 8 /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R1_001.fastq.gz /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R2_001.fastq.gz' returned non-zero exit status 1.

real	18m27,371s
user	19m42,208s
sys	0m12,165s
```
After trying other fastq files it appears the problem is not coming from kb but from the fastqs. I downloaded these files as SRR12603789_1.fastq.gz and SRR12603789_2.fastq.gz which I renamed as SRR12603789_S1_L001_R1_001.fastq.gz and SRR12603789_S1_L001_R2_001.fastq.gz.
Other fastqs are not giving any error.
```
zcat HESA03_HSB42I_0_G_S17_L001_R2_001.fastq.gz | head
@A00213:234:HT3JKDMXX:1:1101:30617:1000 2:N:0:NTGTTTCC
TATTATCGAAACCATCAGCCTGCTCATTCAACCAATAGCCCTAGCCGTACGCCTAACCGCT
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFF,FFFFFFFFFFF:FFFFFF
@A00213:234:HT3JKDMXX:1:1101:31340:1000 2:N:0:NTGTTTCC
AAGCAGTGGTATCAACGCAGAGTACATGGGGAGAGTAAAAAAAAAAAAACACAGAAGAGAG
+
FFFFFF,FFF,FFFFFFF,,FFFFFFFFFFF,FFFFF:FFFF:F,FFFFFFF::FFFFFFF
@A00213:234:HT3JKDMXX:1:1101:32353:1000 2:N:0:NTGTTTCC
GGCATCTCTTGTGTACTTATTGTTTAAGGTTTCCTCAAACTGTGATTTTTCTGAACACAAT
```
However this one gives the error
```
zcat /mnt/sda3/data/public_data/fastq/SRR12603789/SRR12603789_S1_L001_R2_001.fastq.gz | head
@SRR12603789.1 1/2
CACTCCAGTGCTCAGCTTGCACCCTGGCACAGGCCAGCAGTTGCTGGAAGTCAGACACCTGCAGATGAAGACCACAGCATCAAGACCCTGTGACCTCTCAAAGGCCCGGTGGAAAGGACACGGGAAGTCTGGGCTAAGAGACAGCAAATA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFF:
@SRR12603789.2 2/2
ATCCCACTCTAGGCATGGCTCCTCTCCACAGGAAAACTCCACTCCAGTGCTCAGCTTGCACCCTGGCACAGGCCAGCAGTTGCTGGAAGTCAGACACCTGCAGATGAAGACCACAGCATCAAGACCCTGTGACCTCTCAAAGGCCCGGTG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFF
@SRR12603789.3 3/2
CAATGGCCCATCCCACTCTAGGCATGGCTCCTCTCCACAGGAAAACTCCACTCCAGTGCTCAGCTTGCACCCTGGCACAGGCCAGCAGTTGCTGGAAGTCAGACACCTGCAGATGAAGACCACAGCATCAAGACCCTGTGACCTCTCAAA
```
Both samples have been processed with cellranger and velocyto.py without issues
Could someone please have a look at the last file and tell me if there is something wrong with it?
Thank you

**Comment by gaofan83** [comment]
A common mistake when running Kallisto bus is use of the wrong 10XG technology  (v2 26bp, v3 28bp) option. From the SRA database (https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12603789), we can see SRR12603789 should be 10Xv2 (R1 reads 26bp), not 10Xv3. Cellranger automatically detects v2 or v3 chemistry so that users don't need to specify that option.

**Comment by kaizen89** [comment]
I was using indeed v3 as the authors mention in their paper. I should have verified that. Thanks a lot
