### ISSUE TITLE
error message tracing back to get_kallisto_version 

### ISSUE THREAD

**Issue by sanjayrsrivatsan** [pachterlab/kallistobustools#24]
Hi,
I'm trying to analyze some data and I keep getting the following error. I've tried adding the flags `--kallisto` and `--bustools` without any luck.  Any help or guidance would be appreciated. 

Call -- 
```kb count \
-i /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/kallisto_zg11/danio_rerio_kb.idx \
-g /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/kallisto_zg11/danio_rerio_kb.idx/t2g.txt \
-x 10xv2 \
--dry-run \
--bustools /net/gs/vol3/software/modules-sw/bustools/0.40.0/Linux/CentOS7/x86_64/bin/bustools \
--kallisto /net/gs/vol3/software/modules-sw/kallisto/0.46.2/Linux/CentOS7/x86_64/bin/kallisto \
--workflow lamanno \
-c1 /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/kallisto_zg11/cdna_t2c.txt \
-c2 /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/kallisto_zg11/intron_t2c.txt \
-o /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/SRA_PRJNA564810/SRR10095964/ \
 /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/SRA_PRJNA564810/SRR10095964/SRR8599150_S1_L001_R1_001.fastq.gz \
 /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/SRA_PRJNA564810/SRR10095964/SRR8599150_S1_L001_R2_001.fastq.gz&
``` 
 Error --
```[sanjays@t003 SRR10095964]$ mkdir -p /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/SRA_PRJNA564810/SRR10095964/tmp
rm -rf /net/trapnell/vol1/home/sanjays/projects/published_data_nobackup/Miller/SRA_PRJNA564810/SRR10095964/tmp
Traceback (most recent call last):
  File "/net/gs/vol3/software/modules-sw-python/3.6.4/kb-python/0.26.0/Linux/CentOS7/x86_64/bin/kb", line 11, in <module>
    load_entry_point('kb-python==0.26.0', 'console_scripts', 'kb')()
  File "/net/gs/vol3/software/modules-sw-python/3.6.4/kb-python/0.26.0/Linux/CentOS7/x86_64/lib/python3.6/site-packages/kb_python-0.26.0-py3.6.egg/kb_python/main.py", line 866, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/net/gs/vol3/software/modules-sw-python/3.6.4/kb-python/0.26.0/Linux/CentOS7/x86_64/lib/python3.6/site-packages/kb_python-0.26.0-py3.6.egg/kb_python/main.py", line 229, in parse_count
    temp_dir=temp_dir
  File "/net/gs/vol3/software/modules-sw-python/3.6.4/kb-python/0.26.0/Linux/CentOS7/x86_64/lib/python3.6/site-packages/kb_python-0.26.0-py3.6.egg/kb_python/count.py", line 1480, in count_velocity
    STATS.start()
  File "/net/gs/vol3/software/modules-sw-python/3.6.4/kb-python/0.26.0/Linux/CentOS7/x86_64/lib/python3.6/site-packages/kb_python-0.26.0-py3.6.egg/kb_python/stats.py", line 47, in start
    'version': '.'.join(str(i) for i in get_kallisto_version())
  File "/net/gs/vol3/software/modules-sw-python/3.6.4/kb-python/0.26.0/Linux/CentOS7/x86_64/lib/python3.6/site-packages/kb_python-0.26.0-py3.6.egg/kb_python/utils.py", line 254, in get_kallisto_version
    match = VERSION_PARSER.match(p.stdout.read())
AttributeError: 'NoneType' object has no attribute 'stdout'

**Comment by sanjayrsrivatsan** [comment]
This error is resolved when kb-python is installed using python/3.7.7 as opposed to python/3.6.4.
