### ISSUE TITLE
Error: gtf argument when running kb ref: FileNotFoundError: [Errno 2] No such file or directory: 'gtf'

### ISSUE THREAD

**Issue by McKSal** [pachterlab/kallistobustools#56]
Hello, 
I have successfully downloaded kb using this command: 
pip install kb-python

And can print the help page with: 
kb -h

However when I run the kb ref command I get an error. 
The command (the sample is named BMNo6): 
kb ref -i No6_sulcia_INDEX -g No6_sulcia_T2G -f1 BMNo6_sulcia.fasta gtf BMNo6_sulcia.gtf

I get this error: 
[2023-11-17 16:33:03,803]    INFO [ref] Preparing gtf, BMNo6_sulcia.gtf
[2023-11-17 16:33:03,841] WARNING [main] Gene `SULC_00001_gene` has no transcripts. The entire gene will be marked as a transcript and an exon with ID `SULC_00001_gene`.
[2023-11-17 16:33:03,842] WARNING [main] Gene `SULC_00002_gene` has no transcripts. The entire gene will be marked as a transcript and an exon with ID `SULC_00002_gene`.
[2023-11-17 16:33:03,842] WARNING [main] Gene `SULC_00003_gene` has no transcripts. The entire gene will be marked as a 
****I TRUNCATED THIS TO SAVE SPACE****
[2023-11-17 16:33:03,871] WARNING [main] Gene `SULC_00237_gene` has no transcripts. The entire gene will be marked as a transcript and an exon with ID `SULC_00237_gene`.
[2023-11-17 16:33:03,876]    INFO [ref] Splitting genome gtf into cDNA at /Users/mckinleesalazar/Desktop/Dis_stuff/Data/sulcia_transcript/tmp/tmpj3lniqer
[2023-11-17 16:33:03,876]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kb_python/main.py", line 1305, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kb_python/main.py", line 292, in parse_ref
    ref(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kb_python/ref.py", line 492, in ref
    cdna_temp_path = ngs.fasta.split_genomic_fasta_to_cdna(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ngs_tools/fasta/__init__.py", line 29, in split_genomic_fasta_to_cdna
    with Fasta(fasta_path, 'r') as f_in, Fasta(out_path, 'w') as f_out:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ngs_tools/fasta/Fasta.py", line 20, in __init__
    super(Fasta, self).__init__(path, mode)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ngs_tools/utils.py", line 510, in __init__
    self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ngs_tools/utils.py", line 559, in _open
    self.fp = open_as_text(self.path, self.mode)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ngs_tools/utils.py", line 327, in open_as_text
    return gzip.open(path, f'{mode}t') if is_gzip(path) else open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'gtf'

I am confused. the first line says "...Preparing gtf, BMNo6_sulcia.gtf" so it seems to be finding the .gtf at first? But then the final line says "FileNotFound.... no such file or directory: 'gtf'". 

When I remove the gtf: 
kb ref -i No6_sulcia_INDEX -g No6_sulcia_T2G -f1 BMNo6_sulcia.fasta BMNo6_sulcia.gtf 

I get this error: 

usage: kb ref [-h] [--tmp TMP] [--keep-tmp] [--verbose] -i INDEX -g T2G -f1 FASTA [--include-attribute KEY:VALUE | --exclude-attribute KEY:VALUE] [-f2 FASTA] [-c1 T2C] [-c2 T2C]
              [-d {human,mouse,linnarsson}] [-k K] [--workflow {standard,lamanno,nucleus,kite}] [--overwrite] [--kallisto KALLISTO] [--bustools BUSTOOLS]
              fasta gtf [feature]
kb ref: error: the following arguments are required: gtf

I have attached a screenshot (GitHub is not allowing me to attach the actual file-- sorry) my gtf file for reference. I have also attached the bash script I used to convert my genome's .gff (screenshot also attached) to .gtf because I am wondering if the problem is the format of the gtf file itself. 

Thanks in advance for any help you are able to offer, 
McKinlee 

<img width="895" alt="gff2gtf-script-screenshot" src="https://github.com/pachterlab/kallistobustools/assets/110622228/523776d6-e0f4-438e-ae92-0fa8cf443890">
<img width="1320" alt="gffscreenshot" src="https://github.com/pachterlab/kallistobustools/assets/110622228/2a1214f2-c54a-4682-a0b9-8561b7b74921">
<img width="872" alt="gtfscreenshot" src="https://github.com/pachterlab/kallistobustools/assets/110622228/bc45faa2-4178-4646-8d98-84543a678333">

**Comment by Yenaled** [comment]
An output file must be provided after -f1.

For example, you could do:

kb ref -i No6_sulcia_INDEX -g No6_sulcia_T2G -f1 output.fasta BMNo6_sulcia.fasta gtf BMNo6_sulcia.gtf

That should work. The -f1 argument is the file name where you want to write the final sequences that are thrown into kallisto index.

**Comment by Yenaled** [comment]
By the way, please send issues or ask q's on the pachterlab/kallisto repo -- it's much easier for me to check/access things there.

**Comment by McKSal** [comment]
Thanks for replying to me so quickly! In the future I will send issues/question there. Is it ok if I ask one more related question on this thread before closing it? 

I got this command to work: 
kb ref -i No6_sulcia_INDEX -g No6_sulcia_T2G -f1 BMNo6_final_output.fasta BMNo6_sulcia.fasta BMNo6_sulcia.gtf

But I am still getting the warning from before: 
[2023-11-17 17:28:06,868] WARNING [main] Gene `SULC_00001_gene` has no transcripts. The entire gene will be marked as a transcript and an exon with ID `SULC_00001_gene`.

And I get this for all 237 genes resulting in all three output files being empty. In this situation what does "no transcripts" mean since this is a genome and a genome annotation? Is this because of missing transcript ID in my .gtf or is it another issue? 

Thanks and after this response, I will close the thread.
McKinlee

**Comment by Yenaled** [comment]
Sure, and yeah, that means your GTF file is structured so that it only contains genes -- it is missing transcripts / transcript IDs.

A typical GTF file (like the mouse GTF file from Ensembl) would contain both transcript and gene IDs and positional information.

**Comment by McKSal** [comment]
Ok great! thanks again. 
McKinlee
