### ISSUE TITLE
Issue with kb count

### ISSUE THREAD

**Issue by lucasinchausti** [pachterlab/kallistobustools#57]
Hello, I'm having an error that i cant understand when trying to get my count matrix with kb count:

$ kb count -i index.idx -g t2g.txt -t 15 --em --filter --loom -o out_em_algorithm_filter/ -x 10XV3 /media/Disco6/lucas/single_cell/segunda_corrida/scRNAseqTc_S1_L008_R1_001.fastq.gz /media/Disco6/lucas/single_cell/segunda_corrida/scRNAseqTc_S1_L008_R2_001.fastq.gz

Output:

[2024-01-09 11:45:59,780]    INFO [count] Using index index.idx to generate BUS file to out_em_algorithm_filter/ from
[2024-01-09 11:45:59,780]    INFO [count]         /media/Disco6/lucas/single_cell/segunda_corrida/scRNAseqTc_S1_L008_R1_001.fastq.gz
[2024-01-09 11:45:59,781]    INFO [count]         /media/Disco6/lucas/single_cell/segunda_corrida/scRNAseqTc_S1_L008_R2_001.fastq.gz
[2024-01-09 11:46:01,211]   ERROR [count]
[bus] Note: Strand option was not specified; setting it to --fr-stranded for specified technology
[2024-01-09 11:46:01,212]   ERROR [main] An exception occurred
Traceback (most recent call last):
  File "/home/linchausti/miniconda3/envs/kb/lib/python3.8/site-packages/kb_python/main.py", line 1618, in main
    COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
  File "/home/linchausti/miniconda3/envs/kb/lib/python3.8/site-packages/kb_python/main.py", line 703, in parse_count
    count(
  File "/home/linchausti/.local/lib/python3.8/site-packages/ngs_tools/logging.py", line 62, in inner
    return func(*args, **kwargs)
  File "/home/linchausti/miniconda3/envs/kb/lib/python3.8/site-packages/kb_python/count.py", line 1279, in count
    bus_result = kallisto_bus(
  File "/home/linchausti/miniconda3/envs/kb/lib/python3.8/site-packages/kb_python/count.py", line 203, in kallisto_bus
    run_executable(command)
  File "/home/linchausti/miniconda3/envs/kb/lib/python3.8/site-packages/kb_python/dry/__init__.py", line 25, in inner
    return func(*args, **kwargs)
  File "/home/linchausti/miniconda3/envs/kb/lib/python3.8/site-packages/kb_python/utils.py", line 203, in run_executable
    raise sp.CalledProcessError(p.returncode, ' '.join(command))
subprocess.CalledProcessError: Command '/home/linchausti/miniconda3/envs/kb/bin/kallisto bus -i index.idx -o out_em_algorithm_filter/ -x 10XV3 -t 15 /media/Disco6/lucas/single_cell/segunda_corrida/scRNAseqTc_S1_L008_R1_001.fastq.gz /media/Disco6/lucas/single_cell/segunda_corrida/scRNAseqTc_S1_L008_R2_001.fastq.gz' died with <Signals.SIGILL: 4>.

Does anyone got this error before and knows whats the problem? Thanks!

Lucas

**Comment by Yenaled** [comment]
1. What version are you running?

2. What are you generating a loom file for?

3. As mentioned in multiple other GitHub issues, Signals.SIGILL: 4 typically means you have to install kallisto from source.

4. Post issues on the kallisto or, preferably, the kb-python github page -- it's more convenient for me to respond on those pages

**Comment by lucasinchausti** [comment]
Hello!
Thank you very much. I'll try to install kallisto from source. 
Im using these versions:
kb_python 0.28.1
kallisto: 0.50.1 
bustools: 0.43.2 

Sorry, next time i'll post on the kb/python github page :)

**Comment by Yenaled** [comment]
Sounds good -- install kallisto from source, and also, upgrade kb-python to the latest version (0.28.2).
